const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');

function ensureDir(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

function stripHtml(html) {
  if (!html) return '';
  return html
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<\/p>/gi, '\n')
    .replace(/<\/div>/gi, '\n')
    .replace(/<\/li>/gi, '\n')
    .replace(/<\/h[1-6]>/gi, '\n')
    .replace(/<[^>]*>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&')
    .replace(/\n\s*\n/g, '\n')
    .trim();
}

function extractHeading(html, level) {
  const regex = new RegExp(`<h${level}[^>]*>([^<]*)<\\/h${level}>`, 'i');
  const match = html.match(regex);
  return match ? match[1] : null;
}

function exportInvoicePdf(invoice, outputDir, explicitFilePath) {
  const filePath = explicitFilePath || path.join(outputDir, `${invoice.invoice_number}.pdf`);
  ensureDir(path.dirname(filePath));

  const doc = new PDFDocument({ margin: 50 });
  const stream = fs.createWriteStream(filePath);
  doc.pipe(stream);

  // Header
  doc.fontSize(24).text('INVOICE', { align: 'right' });
  doc.moveDown(0.5);
  doc.fontSize(11).text(`Invoice #: ${invoice.invoice_number}`, { align: 'right' });
  doc.text(`Issue Date: ${invoice.issue_date}`, { align: 'right' });
  doc.text(`Due Date: ${invoice.due_date}`, { align: 'right' });

  // Bill To section
  doc.moveDown(2);
  doc.fontSize(12).text('Bill To:', { underline: true });
  doc.fontSize(11);
  doc.text(invoice.client_name || 'N/A');
  if (invoice.client_company) doc.text(invoice.client_company);
  if (invoice.client_email) doc.text(invoice.client_email);
  if (invoice.client_country) doc.text(invoice.client_country);

  // Rich document content
  if (invoice.document_html) {
    doc.moveDown(2);
    const documentContent = stripHtml(invoice.document_html);
    doc.fontSize(10).text(documentContent, { align: 'left', width: 450 });
  } else {
    // Fallback to service description
    doc.moveDown(1.5);
    doc.fontSize(12).text('Service Description', 50, doc.y, { continued: true });
    doc.text('Amount', 430, doc.y, { align: 'right' });
    doc.moveTo(50, doc.y + 5).lineTo(550, doc.y + 5).stroke();

    doc.moveDown();
    doc.fontSize(11).text(invoice.service_description, 50, doc.y, { width: 360 });
    doc.text(`${invoice.currency} ${Number(invoice.amount || 0).toFixed(2)}`, 430, doc.y - 15, { width: 120, align: 'right' });
  }

  // Payment section
  doc.moveDown(2);
  doc.fontSize(12).text('Payment Terms:', { underline: true });
  doc.fontSize(11).text(invoice.payment_terms || 'Upon receipt');

  // Total
  doc.moveDown(2);
  doc.fontSize(14).text(`Total: ${invoice.currency} ${Number(invoice.amount || 0).toFixed(2)}`, { align: 'right' });
  doc.moveDown(2);
  doc.fontSize(10).fillColor('#555').text('Generated by WorkOrbit Freelance Manager', { align: 'center' });

  doc.end();

  return new Promise((resolve, reject) => {
    stream.on('finish', () => resolve(filePath));
    stream.on('error', reject);
  });
}

module.exports = { exportInvoicePdf };
